
### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

> {% client.global.set('token', response.body.token);%}

### seed users
GET {{host}}/seeds/users

### seed soups
GET {{host}}/seeds/soups

### seed soups
GET {{host}}/seeds/seed

### create user
POST {{host}}/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@qq.com",
  "password": "test"
}

### update user
PUT {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "name": "fuck22"
}

### get user
GET {{host}}/users/profile
Authorization: Bearer {{token}}

### get user star soups
GET {{host}}/users/2/starSoups

### get user star comments
GET {{host}}/users/2/starComments

### get soup by id
GET {{host}}/soups/1

### create soup
POST {{host}}/soups
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "然而，TypeScript会认为这段代码可能存在bug。 对象字面量会被特殊对待而且会经过额外属性检查，当将它们赋值给变量或作为参数传递的时候。 如果一个对象字面量存在任何“目标类型”不包含的属性时，你会得到一个错误。",
  "more": {
    "reference": "https://github.com/buuug7",
    "npm": "https://npmjs.com/buuug7"
  }
}

### update soup
PUT {{host}}/soups/26
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "such more useful clean my home222"
}

### delete soup
DELETE {{host}}/soups/28
Authorization: Bearer {{token}}

### list soup
### query: currentPage, perPage, username, content, createdAt(YYYYMMDD)
GET {{host}}/soups?currentPage=1&createdAt=<=&createdAt=20201020&username=&content=
Authorization: Bearer {{token}}

### star soup
POST {{host}}/soups/1/star
Authorization: Bearer {{token}}

### unStar soup
POST {{host}}/soups/1/unStar
Authorization: Bearer {{token}}

### get soup star count
GET {{host}}/soups/1/starCount

### is star by request user
GET {{host}}/soups/1/isStarByRequestUser
Authorization: Bearer {{token}}

### get soup comments
GET {{host}}/soups/1/comments

### comment on soup
POST {{host}}/soups/1/comment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "my first comment on soup one "
}

### reply comment
POST {{host}}/comments/1/reply
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "I reply the first comment"
}

### star comment
POST {{host}}/comments/1/star
Authorization: Bearer {{token}}

### unStar comment
POST {{host}}/comments/1/unStar
Authorization: Bearer {{token}}

### get comment star count
GET {{host}}/comments/1/starCount

### get comment star users
GET {{host}}/comments/1/starUsers

### get one comment
GET {{host}}/comments/1

###




