
### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

> {% client.global.set('token', response.body.access_token);%}


### seed users
GET {{host}}/seeds/users

### seed soups
GET {{host}}/seeds/soups


###
GET {{host}}/users/profile
Authorization: Bearer {{token}}

###
POST {{host}}/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@qq.com",
  "password": "test"
}

### get soup by id
GET {{host}}/soups/26

### create soup
POST {{host}}/soups
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "3然而，TypeScript会认为这段代码可能存在bug。 对象字面量会被特殊对待而且会经过额外属性检查，当将它们赋值给变量或作为参数传递的时候。 如果一个对象字面量存在任何“目标类型”不包含的属性时，你会得到一个错误。",
  "more": {
    "reference": "https://github.com/buuug7",
    "npm": "https://npmjs.com/buuug7"
  }
}

### update soup
PUT {{host}}/soups/26
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "such more useful clean my home222"
}

### delete soup
DELETE {{host}}/soups/28
Authorization: Bearer {{token}}

### list soup
### query: currentPage, perPage, username, content, createdAt(YYYYMMDD)
GET {{host}}/soups?currentPage=1&createdAt=<=&createdAt=20201020&username=buuug7&content=
Authorization: Bearer {{token}}

### star soup
POST {{host}}/soups/star/34
Authorization: Bearer {{token}}

### unStar soup
POST {{host}}/soups/unStar/34
Authorization: Bearer {{token}}

### comment soup
POST {{host}}/soups/1/comment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "my first comment on soup one "
}

### get soup comments
GET {{host}}/soups/1/comments

### reply comment
POST {{host}}/comments/2/reply
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "I reply the first comment"
}

###

