
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

> {% client.global.set('token', response.body.access_token);%}

###


GET http://localhost:3000/user/profile
Authorization: Bearer {{token}}

###
