
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "buuug7",
  "password": "123"
}

> {% client.global.set('token', response.body.access_token) %}

###


GET http://localhost:3000/user/profile
Authorization: Bearer {{token}}

###
